name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  OPENAI_API_KEY: "dummy-value"
  RUST_BACKTRACE: 1

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Download data.tar.gz
        run: wget https://github.com/anandijain/leetcode_evals/releases/download/0.1.0/data.tar.gz
      - name: Unpack data.tar.gz to ./data/
        run: |
          mkdir -p data/
          tar -xzf data.tar.gz -C data/
      - name: Move contents up one level
        run: mv data/data/* data/data/ || true
      - name: List contents of data folder
        run: ls -al data/data/
    #   - run: cargo build --verbose
    #   - run: cargo test --verbose
